version: '2'
services:
  halitran-app:
    image: halitran
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://halitran-postgresql:5432/halitran
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  halitran-postgresql:
    extends:
      file: postgresql.yml
      service: halitran-postgresql
